import type { Metadata } from "next";

// Components
import Navbar from "./components/navbar";

// Styles
import "./globals.scss";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;